	  <!-- SCRIPTS -->
	<script type="text/javascript" src="./public/js/particles.min.js"></script>
	<script type="text/javascript" src="./public/js/jquery.js"></script>
	<script type="text/javascript" src="./public/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="./public/js/particles.min.js"></script>
	<script type="text/javascript" src="./public/js/app.js"></script>
	<script type="text/javascript" src="./public/js/jquery.parallax.js"></script>
	<script type="text/javascript" src="./public/js/smoothscroll.js"></script>
	<script type="text/javascript" src="./public/js/custom.js"></script>